// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUgiZBJxsHOwyP2bnYjfMzjltI9z-8CGg',
    appId: '1:267654077372:web:5f63f3faa062fb51cce9b9',
    messagingSenderId: '267654077372',
    projectId: 'order-app-66e8f',
    authDomain: 'order-app-66e8f.firebaseapp.com',
    storageBucket: 'order-app-66e8f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcsQhnUymTRsoD-fozUHkcX9MwZVRx9VI',
    appId: '1:267654077372:android:7bbaacf43c2f6061cce9b9',
    messagingSenderId: '267654077372',
    projectId: 'order-app-66e8f',
    storageBucket: 'order-app-66e8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATj7FmdIlQXM3hpHQvJENA4FmeWKMSQas',
    appId: '1:267654077372:ios:2883c20a96018501cce9b9',
    messagingSenderId: '267654077372',
    projectId: 'order-app-66e8f',
    storageBucket: 'order-app-66e8f.firebasestorage.app',
    iosBundleId: 'com.ecommerce.ecommerceApp',
  );
}
